name: Build and Release Documentation
on:
  push:
    branches: ['main']
    paths:
      - 'docs/**'
      - '.github/workflows/docu-deployment.yml'
permissions: 
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: |
          cd docs
          npm ci
      - name: Build Documentation
        run: |
          cd docs
          npm run build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: docs/dist
