name: Linting
on: [pull_request]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    # Checkout this repo
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 1
    - name: Clone askui-vale repository for styles
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'askui'
        repository: 'askui-vale'
    # Make styles folder
    - name: Create folder
      run: |
        mkdir -p .github/styles
        cp -R askui-vale/styles/* .github/styles/
    # Lint with Vale
    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        files: '["README.md", "docs/docs/askui-studio"]'
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        REVIEWDOG_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
